import { Book, Category, ReaderSettings } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-all', name: 'All', order: 0, isDefault: true, icon: 'book-open' },
  { id: 'cat-reading', name: 'Currently Reading', order: 1, isDefault: true, icon: 'clock' },
  { id: 'cat-favorites', name: 'Favorites', order: 2, isDefault: false, icon: 'heart' },
  { id: 'cat-tech', name: 'Tech & Code', order: 3, isDefault: false, icon: 'code' },
  { id: 'cat-comics', name: 'Manga & Comics', order: 4, isDefault: false, icon: 'sparkles' },
  { id: 'cat-completed', name: 'Completed', order: 5, isDefault: false, icon: 'check-circle' },
];

export const INITIAL_SETTINGS: ReaderSettings = {
  readingMode: 'long_strip',
  readerTheme: 'oled',
  cropBorders: false,
  splitWidePages: false,
  rotateWidePages: false,
  doubleTapToZoom: true,
  disableZoomOut: false,
  sidePadding: 0,
  keepScreenOn: true,
  volumeKeyNavigation: false,
  showActionsOnLongTap: true,
  invertTapZones: false,
};

export const SAMPLE_BOOKS: Book[] = [
  {
    id: 'sample-1',
    title: 'Modern Software Engineering',
    author: 'Dave Farley',
    coverColor: '#E91E63',
    description: 'A practical guide to modern software architecture, continuous delivery, and scalable systems engineering.',
    uri: 'sample://modern_software_engineering.pdf',
    fileSize: 4520100,
    totalPages: 48,
    currentPage: 14,
    categoryIds: ['cat-all', 'cat-reading', 'cat-tech'],
    addedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    lastReadAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    status: 'reading',
    rating: 5,
    bookmarks: [
      { id: 'bm-1', page: 5, title: 'Chapter 1: Iterative Design', createdAt: new Date().toISOString() },
      { id: 'bm-2', page: 12, title: 'Modular Architecture Principles', createdAt: new Date().toISOString() },
    ],
    readingTimeMinutes: 45,
    isSample: true,
  },
  {
    id: 'sample-2',
    title: 'Mihon Reader & UX Aesthetics',
    author: 'Tachiyomi & Mihon Community',
    coverColor: '#006874',
    description: 'Deep dive into Mihon reader user interface, long strip webtoon navigation, custom color themes, and offline data backups.',
    uri: 'sample://mihon_reader_ux.pdf',
    fileSize: 3120000,
    totalPages: 32,
    currentPage: 32,
    categoryIds: ['cat-all', 'cat-favorites', 'cat-completed'],
    addedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    lastReadAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'completed',
    rating: 5,
    bookmarks: [
      { id: 'bm-3', page: 1, title: 'Mihon Reader Architecture', createdAt: new Date().toISOString() },
    ],
    readingTimeMinutes: 62,
    isSample: true,
  },
  {
    id: 'sample-3',
    title: 'Cyberpunk Odyssey Vol. 1',
    author: 'K. Takahashi & Studio Nexus',
    coverColor: '#882444',
    description: 'High-octane graphic novel set in a neon futuristic city. Features vertical long-strip manga scrolling visuals.',
    uri: 'sample://cyberpunk_odyssey.pdf',
    fileSize: 12400000,
    totalPages: 60,
    currentPage: 8,
    categoryIds: ['cat-all', 'cat-reading', 'cat-comics'],
    addedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lastReadAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    status: 'reading',
    rating: 4,
    bookmarks: [],
    readingTimeMinutes: 20,
    isSample: true,
  },
  {
    id: 'sample-4',
    title: 'TypeScript for Mobile Developers',
    author: 'Dan Abramov & Community',
    coverColor: '#1E1E2E',
    description: 'Comprehensive handbook for building robust, type-safe cross-platform mobile apps with React Native & Expo.',
    uri: 'sample://typescript_mobile_dev.pdf',
    fileSize: 5800000,
    totalPages: 84,
    currentPage: 1,
    categoryIds: ['cat-all', 'cat-tech'],
    addedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    lastReadAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'unread',
    rating: 0,
    bookmarks: [],
    readingTimeMinutes: 0,
    isSample: true,
  },
  {
    id: 'sample-5',
    title: 'The Art of Offline-First Mobile Apps',
    author: 'Pawan & Open Source Guild',
    coverColor: '#2DD4BF',
    description: 'Designing resilient local-first data storage, JSON backup export/import, and instant sync across Android devices.',
    uri: 'sample://offline_first_mobile.pdf',
    fileSize: 2900000,
    totalPages: 40,
    currentPage: 18,
    categoryIds: ['cat-all', 'cat-reading', 'cat-favorites', 'cat-tech'],
    addedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    lastReadAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    status: 'reading',
    rating: 5,
    bookmarks: [
      { id: 'bm-4', page: 18, title: 'JSON Import & Export Schema', createdAt: new Date().toISOString() },
    ],
    readingTimeMinutes: 35,
    isSample: true,
  },
];
